package jopenjpeg2;

import com.sun.jna.Structure;

/**
 * <i>native declaration : line 2</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class jopj_ImgInfo extends Structure {
    public int width;
    public int height;
    public int num_components;
    public int num_resolutions_max;
    public int num_layers;
    public int num_tiles;
    public int num_x_tiles;
    public int num_y_tiles;
    public int tile_x_offset;
    public int tile_y_offset;
    public int tile_width;
    public int tile_height;
    /// Taken from first component
    public int prec;
    public int factor;
    public int resno_decoded;
    public int sgnd;
    public int bpp;
    public int x0;
    public int y0;
    public int dx;
    public int dy;
    public int w;
    public int h;

    public jopj_ImgInfo() {
        super();
        initFieldOrder();
    }

    protected void initFieldOrder() {
        setFieldOrder(new String[]{"width", "height", "num_components", "num_resolutions_max", "num_layers", "num_tiles", "num_x_tiles", "num_y_tiles", "tile_x_offset", "tile_y_offset", "tile_width", "tile_height", "prec", "factor", "resno_decoded", "sgnd", "bpp", "x0", "y0", "dx", "dy", "w", "h"});
    }
}
